language: c
# We need at least cmake 2.12, this means we need to use trusty.
# Precise's glibc, etc predates what we are willing to support.
# No reason for sudo.
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - cmake
      - debhelper
      - gcc
      - gcc-6
      - libnl-3-dev
      - libnl-route-3-dev
      - make
      - ninja-build
      - pkg-config
      - python
      - valgrind

      # 32 bit support packages
      - gcc-multilib
      - lib32gcc-6-dev
script:
  - mkdir build build32
  - cd build
  # The goal is warning free compile on latest gcc.
  - CC=gcc-6 CFLAGS=-Werror cmake -GNinja ..
  - ninja

  # 32 bit build
  - cd ../build32
  # travis's trusty is not configured in a way that enables all32 bit
  # packages. We could fix this with some sudo stuff.. For now turn off libnl
  - CC=gcc-6 CFLAGS="-Werror -m32" cmake -GNinja .. -DENABLE_RESOLVE_NEIGH=0
  - ninja
