language: c
# We need at least cmake 2.12, this means we need to use trusty.
# Precise's glibc, etc predates what we are willing to support.
# sudo is required to get the trusty image, and at present to enable llvm 3.9
sudo: required
dist: trusty
addons:
  # We run our builds sequentially in one VM rather than try and use the
  # matrix feature. This is because Travis is unreasonably inefficient
  # doing this APT setup pass.
  apt:
    sources:
      # sourceline because travis won't white list trusty builds, and hasn't
      # whitelisted 3.9
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"
        key_url: "http://apt.llvm.org/llvm-snapshot.gpg.key"
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - clang-3.9
      - cmake
      - debhelper
      - gcc
      - gcc-6
      - libnl-3-dev
      - libnl-route-3-dev
      - libudev-dev
      - make
      - ninja-build
      - pkg-config
      - python
      - valgrind

      # 32 bit support packages
      - gcc-multilib
      - lib32gcc-6-dev

script:
  - buildlib/travis-build
before_deploy:
  - buildlib/github-release
deploy:
  # Deploy assets to Github releases
  # https://docs.travis-ci.com/user/deployment/releases/
  provider: releases
  api_key:
    # This is encrypted OAth token generated by
    # Travis CLI tool (travis setup releases) limited to specific repo.
    secure: G9sQd578nctgaety6f27P4p5nyrEgXdvMs1g+K2Hj7GPWxBpQ1Jm7kUlahcwfnYXpYqXen9b2dzyGzaLxjLL5rv6rbtOYp9SVrvybQrnJwkB0HCERKVMwEPsLPOB2lMouBDfk4+iUGdxtcw8Y5UU/xqKcAjkHkM5YpF5HauEX1Jj+Ep/XpX5DEcsVmFwkDgPKJOZv/eUgz1eVtXNFIvmSwJ+QuuUz64JpEpKMY4u7bFu0+2qWqACj19P/Rnufxpr+o5yoCuVNVptoRHMIWJiWZsrd2IhmL3knBoPoxNXSOWqQCK6DCW1KYOOVVAfFoD4YWhWrt6MuB3hh7lgLkS0rsdG9+iMlosl4SOkWZF8ZTkmrmtt6yx+s18tFdNI46QKzaA4wS/1hktweIFizYvmEwUCU8sNK5y9PMfDoGJGwiF1FzWrnLItKMiib0sTGO4Umgc0DKTazVRlIJYooOOOnBGubRudNx3elBTy4C/txSmqR39/6GYlvcyUDJMqB/oQJj2erQ5Gu8VykW5zjko6+3miX3C7GFVQ781BLxAdyNl4WRjZ9ibzjMbK3MC7f0ho1hST6cvBBmy2UnIdvB6zMayHZ/gtXKsDqE386k5FwSuTLT2V7942uFRVJiEwhVmgmBzbZND7PTj4s9GPrL2HLlJOgZooRZdx/ZcT/YNPFbA=
    file: rdma-core-*.tar.gz
    # Allow asterisks in file names.
    file_glob: true
    skip_cleanup: true
    # Limit scope of deploy to specific repo.
    on:
      repo: linux-rdma/rdma-core
      tags: true
