language: c
# We need at least cmake 2.12, this means we need to use trusty.
# Precise's glibc, etc predates what we are willing to support.
# sudo is required to get the trusty image, and at present to enable llvm 3.9
sudo: required
dist: trusty
addons:
  # We run our builds sequentially in one VM rather than try and use the
  # matrix feature. This is because Travis is unreasonably inefficient
  # doing this APT setup pass.
  apt:
    sources:
      # sourceline because travis won't white list trusty builds, and hasn't
      # whitelisted 3.9
      - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"
        key_url: "http://apt.llvm.org/llvm-snapshot.gpg.key"
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - clang-3.9
      - cmake
      - debhelper
      - dh-systemd
      - fakeroot
      - gcc
      - gcc-6
      - libnl-3-dev
      - libnl-route-3-dev
      - libudev-dev
      - make
      - ninja-build
      - pkg-config
      - python
      - valgrind

      # 32 bit support packages
      - gcc-multilib
      - lib32gcc-6-dev

script:
  - buildlib/travis-build
